### ISSUE TITLE
[BE] feat: 엔진&바디&구동방식의 가격 정보 가져오기 API 관련 논의

### ISSUE THREAD

**Issue by rbgus2002** [softeerbootcamp-2nd/H6-CaArt#101]
## 🚀 설명
<img width="696" alt="image" src="https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/62997391/7155ab3a-a7d2-4f24-9b52-b78a1e65b075">

기존에는 다음과 같이 분리해서 API를 개발하겠다고 말씀 드렸습니다.
1. 차량구성 정보 조회 API => 엔진&바디&구동방식의 정보 가져오기
2. 차량구성 정보 별 가격 조회 API => 엔진&바디&구동방식 별 가격 정보 가져오기

기존에 말씀드렸던 부분이랑 달리 차량구성 정보 조회 API에서 한 번에 넘겨드려도 좋을 거 같습니다.
괜찮으시면 한 번에 가격까지 넘겨드리도록 API 개발해도 괜찮을까요?

**Comment by sey2** [comment]
좋아용 😙

**Comment by sseungki98** [comment]
한번에 줘도 문제 없긴 합니다 👍

**Comment by rbgus2002** [comment]
그러면 AOS, FE 모두 동의하신 걸로 알고 있겠습니다!
