### ISSUE TITLE
[BE] docs: ERD 수정

### ISSUE THREAD

**Issue by mingulmangul** [softeerbootcamp-2nd/H6-CaArt#184]
## 🚀 설명
> 색상 프리뷰 및 라이프스타일 데이터를 위한 테이블을 추가하고, 옵션을 종류별로 나타낼 수 있도록 ERD를 수정합니다.

## 📝 진행상황
- [x] `color_preview` 테이블 추가
- [x] `기본 옵션` & `추가 옵션` & `자식 옵션` 세 종류의 옵션을 Super-Type Sub-Type Relationship 으로 표현
    - [x] 상속 대신 일대일 연관 관계로 연결하는 방식으로 결정!
- [x] 라이프스타일 데이터를 위한 테이블 설계

**Comment by sey2** [comment]
ㄷㄷ 늦은 시간까지 고생이 많으시네요 👍

**Comment by mingulmangul** [comment]
@sey2 ㅋㅋㅋㅋㅋ 저녁에 자고 왔습니당.. 왜 안주무셔요 얼른 자러가세요

**Comment by mingulmangul** [comment]
@rbgus2002 
옵션끼리 공통된 부분은 묶었는데 조금 고민되는 부분이 있어 코멘트 남깁니당

> super-type & sub-type 으로 표현 (상속)

![image](https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/71026706/67a82133-fbb8-4de1-a659-ba34087f6aeb)

상속 관계임이 명확한 것 같기는 한데, 컬럼 개수가 많아지는 것 같습니다. 식별 관계라 두 테이블 동시에 조회 가능하기도 해요.

> 연관 관계만 설정

![image](https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/71026706/75c2a7b5-f7d9-46c2-b8d5-81dfbe92aa49)

그냥 일대일 연관 관계만 설정했습니다. 컬럼이 많아지는 게 별로라면 이렇게 일대일로 연결만 해주고 조인해서 조회해도 괜찮을 것 같아요.
- 추가 옵션 조회 시 -> 자동차 옵션 join 추가 옵션
- 자식 옵션 조회 시 -> 자동차 옵션 join 자식 옵션

**Comment by rbgus2002** [comment]
slack 허들에서 말씀 드렸지만 후자가 좋은 거 같습니다~! 반영해주시고 PR 날려주시면 감사하겠습니다 ㅎㅎ 🙏

**Comment by mingulmangul** [comment]
- 라이프스타일 관련 테이블 추가

![Image](https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/71026706/e3f680c0-c5c2-4c4a-a76c-e511a119c14f)

- 전체 테이블 관계

![Image](https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/71026706/e1ff19a0-1f22-489c-8be6-2f4b7383ee3a)
