### ISSUE TITLE
[BE] deploy: 프론트엔드 배포

### ISSUE THREAD

**Issue by rbgus2002** [softeerbootcamp-2nd/H6-CaArt#328]
## 🚀 설명
> 프론트 웹사이트를 배포한다.

## 📝 진행상황
- [x] S3 버킷 생성, Cloud Front 연동
- [x] 버지니아 북부 인증서로 변경
- [x] Route53 sub domain 생성 및 Cloud Front 연결
- [x] CORS 문제 해결

**Comment by mingulmangul** [comment]
![Image](https://github.com/softeerbootcamp-2nd/H6-CaArt/assets/71026706/5573a58e-e055-4507-ac73-f46d69863cbb)
